-- 1. Create the table
create table public.access_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  ip_address text,
  city text,
  country text,
  user_agent text,
  device_type text,
  description text
);

-- 2. Enable Row Level Security (RLS)
alter table public.access_logs enable row level security;

-- 3. Create a Policy to allow anyone (anon) to INSERT logs
-- (We allow public insertion because we want to log visitors without them being logged in)
create policy "Allow Public Inserts"
on public.access_logs
for insert
to anon
with check (true);

-- 4. Create a Policy to allow reading logs ONLY if you have the service_role key 
-- OR strictly speaking, we rely on the App to fetch them. 
-- For simplicity in this Demov1, we allow anon read but we could restrict it.
-- Let's allow anon read for the Dashboard to work easily with the same key.
create policy "Allow Public Read"
on public.access_logs
for select
to anon
using (true);
